spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/tasks
    username: postgres
    password: 12345678

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
          ddl-auto: update
server:
  servlet:
    context-path: /api