spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tasks?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234 #root

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml

  mail:
    host:  smtp.yandex.ru
    port: 587
    username: Alexandra-panina05@yandex.ru
    password: nvxjbezhltiovbth
#    protocol: smtp
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true

#server:
#  servlet:
#    context-path: /api

blog:
  title: "DevPub"
  subtitle: Рассказы разработчиков
  phone: 7 903 666-44-55
  email: panina.Alexa5@gmail.com
  copyright: Alex Pan
  copyrightFrom: 2021

time:
  captcha:
    task: 0 0 * * * *

upload:
  dir: src/upload
  maxSize: 10 #считать в MBytes
  profileSize: 5  #Мб
  profileDir: src/upload/avatars

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: debug
#        type:
#          descriptor:
#            sql:
#              BasicBinder: trace