spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tasks?createDatabaseIfNotExist=true&characterEncoding=UTF-8&serverTimezone=UTC
#    url: jdbc:postgresql://localhost:5434/tasks
    username: root
    password: 12345678

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml

#server:
#  servlet:
#    context-path: /api

blog:
  title: "DevPub"
  subtitle: Рассказы разработчиков
  phone: 7 903 666-44-55
  email: panina.Alexa5@gmail.com
  copyright: Alex Pan
  copyrightFrom: 2021

time:
  captcha:
    clear: 60  # считать в минутах

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: debug
#        type:
#          descriptor:
#            sql:
#              BasicBinder: trace